/**
 * Formalities engine — real, dynamic entry requirements for a given
 * nationality → destination, generated by Gemini (no static guesses).
 * Always indicative: the UI keeps the "vérifiez France Diplomatie" warning.
 */
import { geminiService } from './gemini.service.js';

export interface FormalityItem {
  key: string;          // passport | visa | eta | evisa | vaccines | advisory
  label: string;
  status: 'green' | 'orange' | 'red';
  detail: string;
}
export interface FormalitiesResult {
  destination: string;
  nationality: string;
  overall: 'green' | 'orange' | 'red';
  items: FormalityItem[];
  updatedAt: string;
  source: 'gemini';
}

export const formalitiesService = {
  async forTrip(input: { nationality: string; destination: string; residence?: string }): Promise<FormalitiesResult> {
    const prompt = `Tu es un expert des formalités de voyage. Pour un voyageur de nationalité "${input.nationality}"${input.residence ? ` résidant en "${input.residence}"` : ''} se rendant à "${input.destination}" (tourisme, court séjour), donne les formalités d'entrée actuelles.
Réponds STRICTEMENT en JSON avec ce schéma :
{"items":[{"key":"passport|visa|eta|evisa|vaccines|advisory","label":"...","status":"green|orange|red","detail":"phrase courte en français"}],"overall":"green|orange|red"}
Règles de couleur : green = aucune action / conforme, orange = vigilance ou démarche simple (ETA/eVisa/validité à surveiller), red = action obligatoire (visa requis, vaccin obligatoire, alerte sécurité). Sois factuel et concis. N'invente pas : en cas de doute, mets orange et invite à vérifier.`;

    let parsed: { items?: FormalityItem[]; overall?: string } | null = null;
    try {
      parsed = (await geminiService.generateJSON(prompt)) as typeof parsed;
    } catch {
      parsed = null;
    }
    const items: FormalityItem[] = Array.isArray(parsed?.items) ? parsed!.items!.map((it) => ({
      key: it.key || 'advisory',
      label: it.label || '',
      status: (['green', 'orange', 'red'].includes(it.status) ? it.status : 'orange') as FormalityItem['status'],
      detail: it.detail || '',
    })) : [];
    // Fallback if the model returned nothing usable.
    if (!items.length) {
      items.push({ key: 'advisory', label: 'À vérifier', status: 'orange', detail: 'Information indisponible pour le moment — vérifiez sur France Diplomatie.' });
    }
    const order = { red: 3, orange: 2, green: 1 } as const;
    const overall = (['green', 'orange', 'red'].includes(parsed?.overall || '')
      ? parsed!.overall
      : items.reduce((acc, it) => (order[it.status] > order[acc] ? it.status : acc), 'green' as FormalityItem['status'])) as FormalitiesResult['overall'];

    return {
      destination: input.destination, nationality: input.nationality,
      overall, items, updatedAt: new Date().toISOString().slice(0, 10), source: 'gemini',
    };
  },
};
